site_name: VidioPy
site_author: Soham Tilekar
site_description: A Python Video Editing Library
site_url: https://github.com/SohamTilekar/vidiopy

repo_name: SohamTilekar/vidiopy
repo_url: https://github.com/SohamTilekar/vidiopy

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.footer
    - search.suggest
    - search.highlight

  logo: media/vidiopy_logo.png
  favicon: media/vidiopy_logo.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SohamTilekar/vidiopy

plugins:
  - search

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
